### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by EvantheGrump** [wildjaffa/ha-brave-summarizer#1]
Hey! I'm new to home assistant, and I was really excited to use your script. I followed your instructions and restarted the HA server. However, when I ask a question in assist, it tells me an unexpected error occurred. Attached is an image. 

![Screenshot 2024-04-23 203928](https://github.com/wildjaffa/ha-brave-summarizer/assets/70341827/a5e21c46-21e6-441c-8150-2290db3dadc0)

I looked at the logs, and something _seems_ to be triggered. Attached is another image. 

![Screenshot 2024-04-23 204447](https://github.com/wildjaffa/ha-brave-summarizer/assets/70341827/933a09e7-400b-484d-9076-42898b00df06)

If you have any insight, please let me know!

**Comment by EvantheGrump** [comment]
Well, I put the API key for brave in the wrong place. Whoops!

**Comment by wildjaffa** [comment]
Glad you were able to figure it out! I might need to put some validations in it to let you know that parameters are missing!
